base_images:
  ansible:
    name: "4.12"
    namespace: ocp
    tag: ansible
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  openstack-installer:
    name: "4.12"
    namespace: ocp
    tag: openstack-installer
  upi-installer:
    name: "4.12"
    namespace: ocp
    tag: upi-installer
releases:
  initial:
    candidate:
      product: ocp
      relative: 1
      stream: nightly
      version: "4.12"
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.12"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: oadp-interop-tests-aws-ipi-ocp-412
  interval: 960h
  steps:
    cluster_profile: aws-cspi-qe
    env:
      BASE_DOMAIN: aws.interop.ccitredhat.com
      SUB_CHANNEL: stable-1.1
      SUB_INSTALL_NAMESPACE: openshift-adp
      SUB_PACKAGE: redhat-oadp-operator
      SUB_SOURCE: redhat-operators
      SUB_TARGET_NAMESPACES: openshift-adp
    test:
    - chain: oadp-interop-scenario
    workflow: ipi-aws
zz_generated_metadata:
  branch: master
  org: rhpit
  repo: interop-tests
  variant: ocp-412-oadp10
